
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  # Mock API service for development
  mock-api:
    image: stoplight/prism:4
    command: mock -h 0.0.0.0 /app/api-spec.yaml
    ports:
      - "4010:4010"
    volumes:
      - ./api:/app
